### ISSUE TITLE
Markdown/HTML in facet labels

### ISSUE THREAD

**Issue by hrbrmstr** [clauswilke/ggtext#2]
```r
library(glue)
library(ggtext)
library(ggplot2)

count(mtcars, cyl, carb) %>% 
  mutate(cyl_lab = as.character(
    glue("Cylinders {cyl} <span style='color:red'>(n={n})</span>")
  )) %>% 
  ggplot(aes(carb, n)) +
  geom_col() +
  facet_wrap(~cyl_lab) +
  theme(
    strip.text = element_markdown(),
    strip.text.x = element_markdown(),
    strip.text.y = element_markdown()
  )
```

![image](https://user-images.githubusercontent.com/509878/62795741-69dd6d00-baa5-11e9-8a19-c38b0250179a.png)

I'll poke at why this isn't working this weekend.

**Comment by clauswilke** [comment]
Probably the faceting code doesn't use `element_render()`/`element_grob()` to generate the labels.

**Comment by hrbrmstr** [comment]
Heh. It does (in `ggstrip()), but _after_ it pre-renders the strip titles with `create_strip_labels()` which uses `title_spec()` and bypasses the dispatch you hook in to. 

I'll poke a bit more then post an issue on {ggplot2}.
